// Code generated by "stringer -type=state"; DO NOT EDIT

package main

import "fmt"

const _state_name = "startidentstrSinglestrDoublenumbermultexpplusminusdivmodlParenrParencommasemicolonequalillegalCharacterunterminatedStringbadlyFormedNumberunknownState"

var _state_index = [...]uint8{0, 5, 10, 19, 28, 34, 38, 41, 45, 50, 53, 56, 62, 68, 73, 82, 87, 103, 121, 138, 150}

func (i state) String() string {
	if i < 0 || i >= state(len(_state_index)-1) {
		return fmt.Sprintf("state(%d)", i)
	}
	return _state_name[_state_index[i]:_state_index[i+1]]
}
